# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/follow_the_trend',
                'doc_host': 'https://ChendongLi.github.io',
                'git_url': 'https://github.com/ChendongLi/follow_the_trend',
                'lib_path': 'follow_the_trend'},
  'syms': {'follow_the_trend.core': {'follow_the_trend.core.foo': ('core.html#foo', 'follow_the_trend/core.py')}}}
